# Generated by Django 5.1.1 on 2024-11-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('nomedoc', models.CharField(max_length=150)),
                ('emaildoc', models.EmailField(max_length=150)),
                ('senhadoc', models.CharField(max_length=128)),
                ('areaexecu', models.CharField(max_length=150)),
                ('numidentdoc', models.IntegerField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('nomemaq', models.CharField(max_length=150)),
                ('catmaq', models.CharField(max_length=150)),
                ('codidentmaq', models.IntegerField(primary_key=True, serialize=False)),
                ('manual_file', models.FileField(default='manuais/manual_default.pdf', upload_to='media/manuais/')),
                ('image_file', models.FileField(default='images/image_default.png', upload_to='media/images/')),
            ],
            options={
                'db_table': 'maquina',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='manutencao_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='manutencao_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('descmanu', models.CharField(max_length=150)),
                ('codmanu', models.IntegerField(primary_key=True, serialize=False)),
                ('tipomanu', models.IntegerField()),
                ('datamanu', models.DateField()),
                ('numidentdoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.docente')),
                ('codidentmaq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.maquina')),
            ],
            options={
                'db_table': 'manutencao',
            },
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codmanu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_codmanu', to='manutencao.manutencao')),
                ('datamanu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_datamanu', to='manutencao.manutencao')),
                ('responmanu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_responmanu', to='manutencao.manutencao')),
                ('tipomanu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarios_tipomanu', to='manutencao.manutencao')),
            ],
            options={
                'db_table': 'Calendario',
            },
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codmanu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_codmanu', to='manutencao.manutencao')),
                ('datamanu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_datamanu', to='manutencao.manutencao')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_imagem', to='manutencao.maquina')),
                ('nomemaq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_nomemaq', to='manutencao.maquina')),
            ],
            options={
                'db_table': 'relatorios',
            },
        ),
        migrations.CreateModel(
            name='StatusMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('codidentmaq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_codidentmaq', to='manutencao.maquina')),
            ],
            options={
                'db_table': 'statusmaquina',
            },
        ),
        migrations.CreateModel(
            name='ManualMaquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manmaq', models.CharField(max_length=255)),
                ('codmanual', models.CharField(max_length=255)),
                ('codidentmaq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuais', to='manutencao.maquina')),
            ],
            options={
                'db_table': 'ManualMaquinas',
                'unique_together': {('codidentmaq', 'codmanual')},
            },
        ),
    ]
