# Generated by Django 5.1.1 on 2024-11-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manutencao',
            options={'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='numidentdoc',
        ),
        migrations.AlterField(
            model_name='calendario',
            name='codmanu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutencao.manutencao'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='datamanu',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='responmanu',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='tipomanu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='tipomanu',
            field=models.CharField(max_length=150),
        ),
    ]
